config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"app#home"

  get "/contact", to: "app#contact"

  get "/articles/:id", to: "app#show", as: "article_show"
  get "/articles/tags/:id", to: "tag#show", as: "tag"

  get '/dashboard', to: "dashboard#index"

  resources :articles, path: "dashboard/articles", except: [:show, :index]
  resources :tags, path: "dashboard/tags", except: [:show, :index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :tags

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    validates :shortdesc, presence: true, length: {minimum: 20, maximum: 200}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
    @featured = Article.all.where(featured: true)
    @articles = Article.all.where(featured: false)
  end

  def show
    @article = Article.find(params[:id])
    if Article.where(id: params[:id].to_i + 1).exists?
      @article_after = {title: Article.find(params[:id].to_i + 1).title, url: "/articles/" + Article.find(params[:id].to_i + 1).id.to_s}
    else
      @article_after = nil
    end
    render "articles/show"
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :tags
    layout :layout_by_resource

    private

    def layout_by_resource
        if devise_controller?
            "devise"
        else
            "application"
        end
    end

    protected
        def tags
            Tag.all
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :authenticate_user!

    def new
        @article = Article.new()
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to :dashboard
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to :dashboard
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to :dashboard, status: :see_other
    end

    private
        def article_params
            params.require(:article).permit(:title, :body, :shortdesc, :featured, :image_url, tag_ids: [])
        end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  def index

    @articles = Article.all
    @tags = Tag.all

  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController

    def show
        @tag = Tag.find(params[:id])
        @articles = @tag.articles
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :authenticate_user!

    def new
        @tag = Tag.new
    end

    def create
        @tag = Tag.new(tag_params)

        if @tag.save
            redirect_to @tag
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @tag = Tag.find(params[:id])
    end
    
    def update
        @tag = Tag.find(params[:id])

        if @tag.update(tag_params)
            redirect_to :dashboard
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
    
        redirect_to dashboard_path, status: :see_other
    end

    private
        def tag_params
            params.require(:tag).permit(:name, :description)
        end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/app/home.html.erb
<% content_for :title do %>
  Logirails
<% end %>

<div class="home">
    <div class="header">
        <h1 class="title">Navigating the world of News</h1>
        <p class="subtitle">Exploring the Tracks of news: Engage, Discover, and Connect</p>
    </div>

    <div class="featured-post">
        <h2>Featured Post</h2>

        <% @featured.each do |article| %>
        <div class="post featured">
            <div class="post-image">
                <a href="<%= article_show_path article %>"><img src="<%= article.image_url %>" alt="Article image"></a>
            </div>
            <div class="post-head">
                <div class="post-infos">
                    <div>
                        <span><a href="#">John Doe</a>・<time><%= article.created_at.strftime("%d %b, %Y  %I:%M %P") %></time></span>
                        <h3 class="post-title"><a href="<%= article_show_path article %>"><%= article.title %></a></h3>
                    </div>           
                    <div>
                        <a href="<%= article_show_path article %>">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="post-svg-link">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25" />
                            </svg>
                        </a>
                    </div>
                </div>

                <div class="post-shortdesc">
                    <a href="<%= article_show_path article %>"><p><%= article.shortdesc %></p>
                    </a>
                </div>
                
                <div class="post-tags">
                    <ul>
                        <% article.tags.each do |tag| %>
                            <a href="<%= tag_path tag %>"><li class="tag"><%= tag.name %></li></a>
                        <% end %>
                    </ul>
                </div>
                
            </div>
        </div>
        <% end %>
    </div>

    <div class="posts">
        <h2>Recent Posts</h2>
        <div class="grid">

            <% @articles.each do |article| %>
            <div class="post">
                <div class="post-image">
                    <a href="<%= article_show_path article %>"><img src="<%= article.image_url %>" alt="Article image"></a>
                </div>
                <div class="post-head">
                    <div class="post-infos">
                        <div>
                            <span><a href="#">John Doe</a>・<time><%= article.created_at.strftime("%d %b, %Y  %I:%M %P") %></time></span>
                            <h3 class="post-title"><a href="<%= article_show_path article %>"><%= article.title %></a></h3>
                        </div>           
                        <div>
                            <a href="<%= article_show_path article %>">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="post-svg-link">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25" />
                                </svg>
                            </a>
                        </div>
                    </div>
    
                    <div class="post-shortdesc">
                        <a href="<%= article_show_path article %>"><p><%= article.shortdesc %></p>
                        </a>
                    </div>
                    
                    <div class="post-tags">
                        <ul>
                            <% article.tags.each do |tag| %>
                                <a href="<%= tag_path tag %>"><li class="tag"><%= tag.name %></li></a>
                            <% end %>
                        </ul>
                    </div>
                    
                </div>
            </div>
            <% end %>
        </div>
        
    </div>

</div>

app/views/app/show.html.erb
<% content_for :title do %>
  <%= @article.title %>
<% end %>

<div class="article">
    <article class="post">

        <h1 class="post-title"><%= @article.title %></h1>

        <div class="post-image">
            <img src="<%= @article.image_url %>" alt="Article image">
        </div>
        <div class="post-head">
            <div class="post-infos">
                <div>
                    <span><a href="#">John Doe</a>・<time><%= @article.created_at.strftime("%d %b, %Y  %I:%M %P") %></time></span>
                </div>           
            </div>

            <div class="post-shortdesc">
                <p><%= @article.shortdesc %></p>
            </div>
            
            <div class="post-tags">
                <ul>
                    <% @article.tags.each do |tag| %>
                        <a href="/articles/tags/<%= tag.id %>"><li class="tag"><%= tag.name %></li></a>
                    <% end %>
                </ul>
            </div>
            
        </div>
    </article>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="field">
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :shortdesc, "Featured:" %>
    <%= form.select :featured, [['Yes', true], ['No', false]] %>
    <% article.errors.full_messages_for(:shortdesc).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :image_url, "Url of image:" %>
    <%= form.text_field :image_url %>
    <% article.errors.full_messages_for(:image_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :shortdesc, "Short description:" %>
    <%= form.text_area :shortdesc %>
    <% article.errors.full_messages_for(:shortdesc).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :body, "Content:" %>
    <%= form.text_area :body %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field select">
    <%= form.label :tag_ids, "Tags:" %>
    <%= form.collection_select(:tag_ids, Tag.all, :id, :name,{:include_hidden => false}, {multiple:true}) %>
    <% article.errors.full_messages_for(:tags_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title do %>
  Edit Article: @article.title
<% end %>

<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/new.html.erb
<% content_for :title do %>
  New Article
<% end %>

<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<% content_for :title do %>
  <%= @article.title %>
<% end %>

<div class="article">
    <article class="post">

        <h1 class="post-title"><%= @article.title %></h1>

        <div class="post-image">
            <img src="<%= @article.image_url %>" alt="Article image">
        </div>
        <div class="post-head">
            <div class="post-infos">
                <div>
                    <span><a href="#">John Doe</a>・<time><%= @article.created_at.strftime("%d %b, %Y  %I:%M %P") %></time></span>
                </div>           
            </div>

            <div class="post-tags">
                <ul>
                    <% @article.tags.each do |tag| %>
                        <a href="/articles/tags/<%= tag.id %>"><li class="tag"><%= tag.name %></li></a>
                    <% end %>
                </ul>
            </div>
        </div>

        <div class="post-body">
            <p><%= @article.body %></p>
        </div>

        <div class="post-footer">
            <% if !@article_after.nil? %>
                <a href="<%= @article_after[:url] %>">
                    <%= @article_after[:title] %> 
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="post-svg-link">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25" />
                    </svg>
                </a>
            <% end %>
            
        </div>
    </article>
</div>

app/views/dashboard/index.html.erb
<% content_for :title do %>
  Dashboard
<% end %>

<div class="dashboard">
    <h1>Dashboard</h1>

    <div class="dashboard-articles-list">

        <div class="dashboard-article-head">
            <h2>Articles</h2>
            <a href="<%= new_article_path %>">New Article</a>
        </div>

        <% @articles.each do |article| %> 
            <div class="dashboard-article-item">
                <div class="dashboard-article-item-title">
                    <p><%= article.title %></p>
                </div>
                <div class="dashboard-article-item-actions">
                    <a href="<%= article_path article %>" class="dashboard-article-item-actions-a">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>  
                    </a>
                    <div class="relative">
                        <button class="dashboard-item-actions-btn">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                            </svg>
                        </button>
                        
                        <div class="dashboard-item-actions-menu">
                            <ul>
                                <li><a href="<%= edit_article_path article %>">Edit</a></li>
                                <li><%= link_to "Delete", article_path(article), data: {
                                    turbo_method: :delete,
                                    turbo_confirm: "Are you sure?"
                                  } %></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>

       
        
        
    </div>

    <div class="dashboard-tags-list">
        <div class="dashboard-tags-head">
            <h2>Tags</h2>
            <a href="<%= new_tag_path %>">New tag</a>
        </div>
        
        <% @tags.each do |tag| %>
            <div class="dashboard-tag-item">
                <div class="dashboard-tag-item-title">
                    <p><%= tag.name %></p>
                </div>
                <div class="dashboard-tag-item-actions">
                    <a href="/articles/tags/<%= tag.id %>" class="dashboard-tag-item-actions-a">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>  
                    </a>

                    <div class="relative">
                        <button class="dashboard-item-actions-btn">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                            </svg>
                        </button>
                        
                        <div class="dashboard-item-actions-menu">
                            <ul>
                                <li><a href="<%= edit_tag_path tag %>">Edit</a></li>
                                <li><%= link_to "Delete", tag_path(tag), data: {
                                    turbo_method: :delete,
                                    turbo_confirm: "Are you sure?"
                                  } %></li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield :title %> | Tech blog (fictive) </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= yield :metas %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "partials/header", tags: tags %>

    <div class="devise-alerts">
      <% if notice %>
        <div class="notice message">
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class="alert message">
          <%= alert %>
        </div>
      <% end %>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <div class="gradient-block"></div>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield :title %> | Tech blog (fictive) </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= yield :metas %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <div class="gradient-block"></div>
    
    <div class="devise-alerts">
      <% if notice %>
        <div class="notice message">
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class="alert message">
          <%= alert %>
        </div>
      <% end %>
    </div>

    <div class="devise-container">
        <div class="devise-image">
            <img src="https://loremflickr.com/1920/1080/paysage" alt="Devise image" />
        </div>
        <div class="devise-content">
            <%= yield %>
        </div>
    </div>
    

  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">      
    <div class="footer-sections">
        <div class="footer-newsletter">
        <h4>Newsletter</h4>
        <p>Want to get update about new posts before everyone, or about events. Just subscribe to our newsletter and get updated !</p>
        <form action="/newsletter" class="footer-newsletter-form">
            <input name="email" type="email" class="input" size="1" placeholder="Enter an email" required autocomplete="email" />
            <button type="submit">Subscribe</button>
        </form>
        </div>
        <div class="footer-links">
        <h4>Usefull links</h4>
        <ul>
            <li><a href="<%= root_path %>">Home</a></li>
            <li><a href="<%= dashboard_path %>">Dashboard</a></li>
            <% if user_signed_in? %>
                <li><%= button_to "Sign out", destroy_user_session_path, method: :delete %> </li>
            <% end %>
            <li><a href="/contact">Contact</a></li>
        </ul>
        </div>

        <div class="footer-informations">
        <h4>Informations</h4>
        <p>Logirails is a fictive tech blog based on Ruby on Rails. </p>
        </div>
    </div>


    <div class="footer-copyright">
        
        <a href="<%= root_path %>" class="logo"><%= image_tag "logo.png" %></a>
        <p>Coypyright &copy; Logirails 2023</p>
    </div>

</footer>

app/views/partials/_header.html.erb
<header class="header">
    <div class="gradient-block"></div>
    <a href="<%= root_path %>" class="logo"><%= image_tag "logo.png" %></a>
    <input class="side-menu" type="checkbox" id="side-menu"/>
    <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>
    <!-- Menu -->
    <nav class="nav">
        <ul class="menu">
            <li><a href="<%= root_path %>">Home</a></li>
            <% tags.each do |tag| %>
                <li><a href="/articles/tags/<%= tag.id %>"><%= tag.name %></a></li>
            <% end %>
         
        </ul>
        <% if user_signed_in? %> 
            <a href="<%= dashboard_path %>"><button class="dashboard-btn">Dashboard</button></a>
        <% end %>
    </nav>
</header>

app/views/tag/show.html.erb
<% content_for :title do %>
  Posts: <%= @tag.name %>
<% end %>

<div class="tag posts">
    <h2>Posts: <%= @tag.name %> </h2>
    <div class="grid">

        <% @articles.each do |article| %>
        <div class="post">
            <div class="post-image">
                <a href="/articles/<%= article.id %>"><img src="<%= article.image_url %>" alt="Article image"></a>
            </div>
            <div class="post-head">
                <div class="post-infos">
                    <div>
                        <span><a href="#">John Doe</a>・<time><%= article.created_at.strftime("%d %b, %Y  %I:%M %P") %></time></span>
                        <h3 class="post-title"><a href="/articles/<%= article.id %>"><%= article.title %></a></h3>
                    </div>           
                    <div>
                        <a href="/articles/<%= article.id %>">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="post-svg-link">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25" />
                            </svg>
                        </a>
                    </div>
                </div>

                <div class="post-shortdesc">
                    <a href="/articles/<%= article.id %>"><p><%= article.shortdesc %></p>
                    </a>
                </div>
                
                <div class="post-tags">
                    <ul>
                        <% article.tags.each do |tag| %>
                            <a href="/articles/tags/<%= tag.id %>"><li class="tag"><%= tag.name %></li></a>
                        <% end %>
                    </ul>
                </div>
                
            </div>
        </div>
        <% end %>
    </div>
    
</div>

app/views/tags/_form.html.erb
<%= form_with model: tag do |form| %>
  <div class="field">
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name %>
    <% tag.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description, "Short description:" %>
    <%= form.text_area :description %>
    <% tag.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% content_for :title do %>
  Edit Tag: @tag.title
<% end %>

<h1>Edit Tag</h1>

<%= render "form", tag: @tag %>

app/views/tags/new.html.erb
<% content_for :title do %>
  New Tag
<% end %>

<h1>New Tag</h1>

<%= render "form", tag: @tag %>